"""Example caller sentences for each intent, used to train the intent classifier.

Intents match skills (``tellerline.router.skills``). Examples are hand-written and kept
separate from the benchmark cases, so classifier accuracy is measured on unseen sentences.
"""

EXAMPLES: dict[str, list[str]] = {
    "identity": [
        "My customer number is 20394857.",
        "Customer number 55128833, date of birth fourth of July 1988.",
        "I was born on the 30th of October 1975.",
        "Here are my details, 66102938 and the 1st of March 1999.",
        "My date of birth is 17/05/1992.",
        "It's 4 4 0 1 2 2 8 7.",
        "Do you need my customer number?",
        "What details do you need to check it's me?",
        "My number's 81726354 and I was born on the 8th of December 1969.",
        "Born the twenty-second of February 1980, number 73920184.",
        "I don't know my customer number.",
        "Where do I find my customer number?",
        "Sure, it's 39485720.",
        "The twelfth of June 1955.",
        "Is it the eight digit number on my statement?",
        "Hang on, let me find my details.",
    ],
    "accounts": [
        "How much money do I have?",
        "Check my savings balance please.",
        "How much is left in my current account?",
        "Can you tell me my available funds?",
        "Did my wages go in?",
        "Has my salary been paid in yet?",
        "What did I spend at the weekend?",
        "Read me my last few payments.",
        "Show me recent transactions on my savings.",
        "What came out of my account this morning?",
        "Am I overdrawn?",
        "How much have I got to spend?",
        "Tell me the last five things I paid for.",
        "What's the most recent payment on my account?",
        "Has the rent gone out yet?",
        "What's the current account sitting at?",
    ],
    "cards": [
        "I can't find my bank card.",
        "My card was stolen.",
        "Block my card please.",
        "Someone has taken my purse with my card in it.",
        "Freeze the card ending 1234.",
        "I left my card in a taxi.",
        "My card got swallowed by the ATM.",
        "My card is bent and doesn't work anymore.",
        "I need a new card.",
        "Can you cancel my card?",
        "I think someone's using my card details.",
        "Put a temporary hold on my card.",
        "My contactless isn't working, can I get a replacement?",
        "The card ending 5678 is missing.",
        "When will my replacement card arrive?",
        "I gave my card number to a scam caller.",
        "I've found my card, can you unblock it?",
        "Please turn my card back on.",
        "Is my card still blocked?",
        "Has my new card been sent out yet?",
        "Is my card working?",
    ],
    "disputes": [
        "There's a payment I don't recognise.",
        "How do I dispute something on my statement?",
        "I was charged twice.",
        "A shop overcharged me.",
        "I didn't make this purchase.",
        "Can I get my money back for a payment I didn't authorise?",
        "Netflix took money after I cancelled.",
        "There's a strange charge from an online store.",
        "Challenge a payment of 40 euro from Lidl.",
        "I was billed for a hotel I never stayed at.",
        "The restaurant charged me the wrong amount.",
        "Refund a duplicate payment.",
        "Report a fraudulent transaction.",
        "I need to query a charge on my account.",
        "Someone bought something online and it wasn't me.",
        "That payment to the petrol station is wrong.",
    ],
    "general": [
        "I want to speak to a person.",
        "Can I talk to a human please?",
        "Put me through to customer service.",
        "I'd like to make a complaint.",
        "How do I apply for a loan?",
        "Can you send money to my brother?",
        "I want to open a new account.",
        "What are your opening hours?",
        "Change my address please.",
        "What's the interest rate on savings?",
        "Can I get a credit card?",
        "Thanks, that's everything.",
        "Goodbye.",
        "No, that's all for today.",
        "Is it going to rain later?",
        "Do you like football?",
        "Are you a robot?",
        "I've lost my job and can't pay my bills.",
        "My mother has died and I need help with her account.",
        "Hello?",
        "Sorry, can you say that again?",
    ],
}
